version: "3"

services:

  neo4j:
    container_name: neo4j
    image: neo4j:latest
    ports:
      - 7474:7474
      - 7687:7687
    environment:
      - NEO4J_AUTH=neo4j/$NEO4J_PASSWORD
      - NEO4J_server_config_strict__validation_enabled=false
    volumes:
      - ./neo4j_db/data:/data
      - ./neo4j_db/logs:/logs
    env_file:
      .env

  flask:
    build:
      context: .
      dockerfile: ./Dockerfile
    command: 'gunicorn --reload --workers 1 -t 3600 --bind 0.0.0.0:5555 main:app'
    ports:
      - "5555:5555"
    volumes:
      - ".:/opt"
      - "/etc/localtime:/etc/localtime:ro"
    depends_on:
      - neo4j
    logging:
      options:
        max-size: 10m
    env_file:
      - .env
